### PR TITLE
Make template more flexible

### LINKED ISSUE #3: Theme does not adapt to aspect ratio
I just wanted to remark that this theme is not adaptive when changing the aspect ratio of the beamer presentation (e.g. via the `aspectratio=169` option in order to yield a 16:9 presentation).
While at least for 16:9 the theme still looks far from terrible, the circles used on e.g. the title slide and the section slides are misaligned on the wider slide format.

I guess in order to solve this, the positioning of the different layout elements would have to be performed using relative page coordinates and some maths to ensure they don't get sheared.

Maybe I find the time and motivation to work on this, maybe not. In any case I just wanted to document this issue here.

### PR DESCRIPTION
**Pull request by Krzmbrzl**
This PR adds several commits that aim to increase the flexibility of this template. The overall changes are
- Make institute-, department, etc. logos optional (not every institute has separate sub-logos)
- Switch out the university logo with the english one (and use a vector graphic instead of a PNG)
- Make the title page, thank you page and section pages adapt to the currently used aspect ratio (before the element placement was off when e.g. switching to a 16:9 format for the slides)
- Center the author in the footer line, if the title has a length that allows for it (aka: overlaps are avoided)
- Always center the author name in its respective circle on the title page

Fixes #3

### CODE REVIEW

**Comment by valentjn** [comment]
Thanks for the PR. CI is failing, could you have a look?

**Comment by Krzmbrzl** [comment]
As far as I can tell [epstopdf](https://www.ctan.org/pkg/epstopdf?lang=en) (part of TeXLive) is not installed and thus it fails to properly embed the university logo which I replaced by a vector graphic in order to be able to losslessly scale it as needed.

I'm currently not sure which sub-package this is a part of in the Ubuntu repos though - I tend to install TL manually instead of through the Ubuntu repos.

**Comment by valentjn** [comment]
Can you replace the EPS with a PDF? This would reduce required dependencies.

**Comment by Krzmbrzl** [comment]
There is no official PDF version of the logo but I could probably just add the EPS in a `standalone` class and compile that using TeX 👀

**Comment by Krzmbrzl** [comment]
Okay even simpler: `epstopdf` already converts the EPS to a PDF in the previous setup. So all I had to do was to copy the auto-generated PDF from there ^^

In theory CI should succeed now.

**Comment by Krzmbrzl** [comment]
Okay I think GitHub Actions malfunctioned - maybe it needs to be restarted manually?

**Review by valentjn — APPROVED** [review]

**Pull request merged**
